---
title: Raspberry Pi と Build HAT を LEGO® に取り付ける
hero_image: images/banner.png
description: Raspberry Pi Build HAT を LEGO® に取り付ける
version: 4
listed: false
copyedit: false
ingedient: true
last_tested: "2020-03-23"
steps:
  - title: Raspberry Pi を LEGO に取り付ける
