---
title: Attach a Raspberry Pi and Build HAT to LEGO®
hero_image: images/banner.png
description: Attach a Raspberry Pi Build HAT to LEGO®
version: 4
listed: false
copyedit: false
ingedient: true
last_tested: "2020-03-23"
steps:
  - 
    title: Attaching a Raspberry Pi to LEGO
